// 36 Secretarías y dependencias de la Alcaldía de Medellín (v1)
export const SECRETARIAS = [
  "Secretaría de Salud",
  "Secretaría de Educación",
  "Secretaría de Movilidad",
  "Secretaría de Hacienda",
  "Secretaría de Gobierno",
  "Secretaría de Seguridad y Convivencia",
  "Secretaría de las Mujeres",
  "Secretaría de Cultura Ciudadana",
  "Secretaría de Inclusión Social",
  "Secretaría de la Juventud",
  "Secretaría de Medio Ambiente",
  "Secretaría de Infraestructura Física",
  "Secretaría de Gestión Humana",
  "Secretaría de Comunicaciones",
  "Secretaría de Desarrollo Económico",
  "Secretaría de Suministros y Servicios",
  "Secretaría de Evaluación y Control",
  "Secretaría de Participación Ciudadana",
  "Secretaría de Gestión y Control Territorial",
  "Secretaría Privada",
  "Secretaría General",
  "Secretaría de No Violencia",
  "Secretaría de Innovación Digital",
  "Departamento Administrativo de Planeación",
  "Departamento Administrativo de Gestión del Riesgo (DAGRD)",
  "Agencia para la Gestión del Paisaje (APP)",
  "INDER Medellín",
  "Metro de Medellín",
  "EPM",
  "ISVIMED",
  "Sapiencia",
  "SIATA",
  "Telemedellín",
  "Museo Casa de la Memoria",
  "Plaza Mayor",
  "Hospital General de Medellín",
] as const;

export const TIPOS_PQRSDS = [
  "Petición",
  "Queja",
  "Reclamo",
  "Sugerencia",
  "Denuncia",
  "Solicitud",
] as const;
