/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransparenciaRouteImport } from './routes/transparencia'
import { Route as PqrsdsRouteImport } from './routes/pqrsds'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SecretariasIndexRouteImport } from './routes/secretarias.index'
import { Route as SecretariasSlugRouteImport } from './routes/secretarias.$slug'

const TransparenciaRoute = TransparenciaRouteImport.update({
  id: '/transparencia',
  path: '/transparencia',
  getParentRoute: () => rootRouteImport,
} as any)
const PqrsdsRoute = PqrsdsRouteImport.update({
  id: '/pqrsds',
  path: '/pqrsds',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SecretariasIndexRoute = SecretariasIndexRouteImport.update({
  id: '/secretarias/',
  path: '/secretarias/',
  getParentRoute: () => rootRouteImport,
} as any)
const SecretariasSlugRoute = SecretariasSlugRouteImport.update({
  id: '/secretarias/$slug',
  path: '/secretarias/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/pqrsds': typeof PqrsdsRoute
  '/transparencia': typeof TransparenciaRoute
  '/secretarias/$slug': typeof SecretariasSlugRoute
  '/secretarias/': typeof SecretariasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/pqrsds': typeof PqrsdsRoute
  '/transparencia': typeof TransparenciaRoute
  '/secretarias/$slug': typeof SecretariasSlugRoute
  '/secretarias': typeof SecretariasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/pqrsds': typeof PqrsdsRoute
  '/transparencia': typeof TransparenciaRoute
  '/secretarias/$slug': typeof SecretariasSlugRoute
  '/secretarias/': typeof SecretariasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/pqrsds'
    | '/transparencia'
    | '/secretarias/$slug'
    | '/secretarias/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/pqrsds'
    | '/transparencia'
    | '/secretarias/$slug'
    | '/secretarias'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/pqrsds'
    | '/transparencia'
    | '/secretarias/$slug'
    | '/secretarias/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  PqrsdsRoute: typeof PqrsdsRoute
  TransparenciaRoute: typeof TransparenciaRoute
  SecretariasSlugRoute: typeof SecretariasSlugRoute
  SecretariasIndexRoute: typeof SecretariasIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transparencia': {
      id: '/transparencia'
      path: '/transparencia'
      fullPath: '/transparencia'
      preLoaderRoute: typeof TransparenciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pqrsds': {
      id: '/pqrsds'
      path: '/pqrsds'
      fullPath: '/pqrsds'
      preLoaderRoute: typeof PqrsdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/secretarias/': {
      id: '/secretarias/'
      path: '/secretarias'
      fullPath: '/secretarias/'
      preLoaderRoute: typeof SecretariasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/secretarias/$slug': {
      id: '/secretarias/$slug'
      path: '/secretarias/$slug'
      fullPath: '/secretarias/$slug'
      preLoaderRoute: typeof SecretariasSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  PqrsdsRoute: PqrsdsRoute,
  TransparenciaRoute: TransparenciaRoute,
  SecretariasSlugRoute: SecretariasSlugRoute,
  SecretariasIndexRoute: SecretariasIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
